### ISSUE TITLE
Update pairedWith property.

### ISSUE THREAD

**Issue by jalleng** [amyeleek/cf-pair-script#5]
Update pairedWith property on the final pairs.  And update pairedWith() function to work with groups of three. Also add functionality to clear pairedWith array once maximum pairs have been reached. Note: Max pairs may be reached before the length of pairedWith is equal to the length of students.  This occurs when two students are not compatible.

**Comment by amyeleek** [comment]
Updated pairedWith, refactored pairedWith. Added clearPairedWith function. Check will have to wait until we have the finished sorted array.

**Comment by amyeleek** [comment]
Updated with a check for if we have hit max pairs.
